create extension if not exists pgcrypto with schema extensions;

create table if not exists public.plans (
  code text primary key check (code in ('free', 'pro', 'team')),
  label text not null,
  box_limit integer not null check (box_limit > 0),
  space_limit integer not null check (space_limit > 0),
  quota_bytes bigint not null check (quota_bytes > 0),
  file_max_bytes bigint not null check (file_max_bytes > 0),
  sort_order smallint not null
);

insert into public.plans (code, label, box_limit, space_limit, quota_bytes, file_max_bytes, sort_order)
values
  ('free', 'Free', 10, 1, 52428800, 15728640, 0),
  ('pro', 'Pro', 50, 3, 1073741824, 104857600, 1),
  ('team', 'Team', 100, 10, 5368709120, 104857600, 2)
on conflict (code) do update set
  label = excluded.label,
  box_limit = excluded.box_limit,
  space_limit = excluded.space_limit,
  quota_bytes = excluded.quota_bytes,
  file_max_bytes = excluded.file_max_bytes,
  sort_order = excluded.sort_order;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  plan text not null default 'free' references public.plans(code),
  plan_expires_at timestamptz,
  extra_spaces integer not null default 0 check (extra_spaces >= 0),
  extra_boxes integer not null default 0 check (extra_boxes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.spaces (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 40),
  space_code text not null unique check (space_code ~ '^[A-Z0-9][A-Z0-9-]{2,23}$'),
  password_hash text,
  owner_id uuid not null references public.profiles(id) on delete restrict,
  box_limit integer not null default 10 check (box_limit > 0),
  quota_bytes bigint not null default 52428800 check (quota_bytes > 0),
  used_bytes bigint not null default 0 check (used_bytes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.space_members (
  space_id uuid not null references public.spaces(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (space_id, user_id)
);

create index if not exists space_members_user_idx on public.space_members (user_id, joined_at);

create table if not exists public.boxes (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 40),
  kind text not null default 'text' check (kind in ('text', 'image', 'file')),
  text_content text,
  r2_key text,
  byte_size bigint not null default 0 check (byte_size >= 0),
  expires_at timestamptz,
  sort_order integer not null default 0,
  locked boolean not null default false,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint boxes_text_size check (text_content is null or octet_length(text_content) <= 10240),
  constraint boxes_kind_shape check (
    (kind = 'text' and r2_key is null and expires_at is null)
    or (kind in ('image', 'file') and text_content is null)
  )
);

create index if not exists boxes_space_order_idx on public.boxes (space_id, sort_order, created_at);

create table if not exists public.upgrade_intents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  space_id uuid references public.spaces(id) on delete set null,
  lever text not null check (lever in ('box_limit', 'space_quota', 'space_limit', 'file_upload')),
  created_at timestamptz not null default now()
);

create index if not exists upgrade_intents_user_idx on public.upgrade_intents (user_id, created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(coalesce(new.email, ''), '@', 1)
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email, display_name)
select
  u.id,
  u.email,
  coalesce(u.raw_user_meta_data ->> 'full_name', split_part(coalesce(u.email, ''), '@', 1))
from auth.users u
on conflict (id) do nothing;

create or replace function public.is_space_member(p_space_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.space_members m
    where m.space_id = p_space_id and m.user_id = auth.uid()
  );
$$;

create or replace function public.is_space_owner(p_space_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.space_members m
    where m.space_id = p_space_id and m.user_id = auth.uid() and m.role = 'owner'
  );
$$;

create or replace function public.shares_space_with(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.space_members mine
    join public.space_members theirs on theirs.space_id = mine.space_id
    where mine.user_id = auth.uid() and theirs.user_id = p_user_id
  );
$$;

create or replace function public.generate_space_code()
returns text
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  raw text;
  candidate text;
  attempts integer := 0;
begin
  loop
    raw := '';
    for i in 1..8 loop
      raw := raw || substr(alphabet, 1 + floor(random() * length(alphabet))::integer, 1);
    end loop;
    candidate := substr(raw, 1, 4) || '-' || substr(raw, 5, 4);
    exit when not exists (select 1 from public.spaces s where s.space_code = candidate);
    attempts := attempts + 1;
    if attempts > 50 then
      raise exception 'SPACE_CODE_EXHAUSTED';
    end if;
  end loop;
  return candidate;
end;
$$;

create or replace function public.boxes_before_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_space public.spaces;
  v_delta bigint;
begin
  if tg_op = 'UPDATE' then
    if old.locked and new.text_content is distinct from old.text_content then
      raise exception 'BOX_LOCKED';
    end if;
    new.space_id := old.space_id;
    new.kind := old.kind;
    new.locked := old.locked;
    new.created_at := old.created_at;
  end if;

  if new.kind = 'text' then
    new.r2_key := null;
    new.expires_at := null;
    new.byte_size := coalesce(octet_length(new.text_content), 0);
  end if;

  new.updated_at := now();
  new.updated_by := auth.uid();

  select * into v_space from public.spaces where id = new.space_id for update;
  if not found then
    raise exception 'SPACE_NOT_FOUND';
  end if;

  if tg_op = 'INSERT' then
    v_delta := new.byte_size;
  else
    v_delta := new.byte_size - old.byte_size;
  end if;

  if v_delta > 0 and v_space.used_bytes + v_delta > v_space.quota_bytes then
    raise exception 'SPACE_QUOTA_EXCEEDED';
  end if;

  return new;
end;
$$;

drop trigger if exists boxes_before_write on public.boxes;
create trigger boxes_before_write before insert or update on public.boxes
for each row execute function public.boxes_before_write();

create or replace function public.boxes_sync_usage()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.spaces
    set used_bytes = used_bytes + new.byte_size, updated_at = now()
    where id = new.space_id;
    return new;
  elsif tg_op = 'UPDATE' then
    if new.space_id = old.space_id then
      update public.spaces
      set used_bytes = greatest(0, used_bytes + (new.byte_size - old.byte_size)), updated_at = now()
      where id = new.space_id;
    else
      update public.spaces
      set used_bytes = greatest(0, used_bytes - old.byte_size), updated_at = now()
      where id = old.space_id;
      update public.spaces
      set used_bytes = used_bytes + new.byte_size, updated_at = now()
      where id = new.space_id;
    end if;
    return new;
  else
    update public.spaces
    set used_bytes = greatest(0, used_bytes - old.byte_size), updated_at = now()
    where id = old.space_id;
    return old;
  end if;
end;
$$;

drop trigger if exists boxes_sync_usage on public.boxes;
create trigger boxes_sync_usage after insert or update or delete on public.boxes
for each row execute function public.boxes_sync_usage();

create or replace function public.enforce_box_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer;
  v_count integer;
begin
  select box_limit into v_limit from public.spaces where id = new.space_id;
  select count(*) into v_count from public.boxes where space_id = new.space_id;
  if v_count >= v_limit then
    raise exception 'BOX_LIMIT_REACHED';
  end if;
  return new;
end;
$$;

drop trigger if exists boxes_enforce_limit on public.boxes;
create trigger boxes_enforce_limit before insert on public.boxes
for each row execute function public.enforce_box_limit();

create or replace function public.current_profile()
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_profile public.profiles;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  select * into v_profile from public.profiles where id = v_user;
  if not found then
    insert into public.profiles (id) values (v_user) returning * into v_profile;
  end if;
  return v_profile;
end;
$$;

create or replace function public.create_space(p_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_profile public.profiles;
  v_plan public.plans;
  v_owned integer;
  v_name text := btrim(coalesce(p_name, ''));
  v_space_id uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'INVALID_SPACE_NAME';
  end if;

  v_profile := public.current_profile();
  select * into v_plan from public.plans where code = v_profile.plan;
  select count(*) into v_owned from public.spaces where owner_id = v_user;

  if v_owned >= v_plan.space_limit + v_profile.extra_spaces then
    raise exception 'SPACE_LIMIT_REACHED';
  end if;

  insert into public.spaces (name, space_code, owner_id, box_limit, quota_bytes)
  values (
    v_name,
    public.generate_space_code(),
    v_user,
    v_plan.box_limit + v_profile.extra_boxes,
    v_plan.quota_bytes
  )
  returning id into v_space_id;

  insert into public.space_members (space_id, user_id, role)
  values (v_space_id, v_user, 'owner');

  return v_space_id;
end;
$$;

create or replace function public.ensure_personal_space()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_space_id uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  perform public.current_profile();

  select id into v_space_id from public.spaces where owner_id = v_user order by created_at limit 1;
  if v_space_id is not null then
    insert into public.space_members (space_id, user_id, role)
    values (v_space_id, v_user, 'owner')
    on conflict (space_id, user_id) do nothing;
    return v_space_id;
  end if;

  select space_id into v_space_id from public.space_members where user_id = v_user order by joined_at limit 1;
  if v_space_id is not null then
    return v_space_id;
  end if;

  return public.create_space('내 공간');
end;
$$;

create or replace function public.rename_space(p_space_id uuid, p_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := btrim(coalesce(p_name, ''));
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'INVALID_SPACE_NAME';
  end if;
  update public.spaces set name = v_name, updated_at = now() where id = p_space_id;
end;
$$;

create or replace function public.set_space_code(p_space_id uuid, p_code text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := upper(btrim(coalesce(p_code, '')));
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  if v_code !~ '^[A-Z0-9][A-Z0-9-]{3,23}$' then
    raise exception 'INVALID_SPACE_CODE';
  end if;
  if exists (select 1 from public.spaces where space_code = v_code and id <> p_space_id) then
    raise exception 'SPACE_CODE_TAKEN';
  end if;
  update public.spaces set space_code = v_code, updated_at = now() where id = p_space_id;
  return v_code;
end;
$$;

create or replace function public.set_space_password(p_space_id uuid, p_password text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  if char_length(coalesce(p_password, '')) < 6 then
    raise exception 'PASSWORD_TOO_SHORT';
  end if;
  update public.spaces
  set password_hash = crypt(p_password, gen_salt('bf', 10)), updated_at = now()
  where id = p_space_id;
end;
$$;

create or replace function public.clear_space_password(p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  update public.spaces set password_hash = null, updated_at = now() where id = p_space_id;
end;
$$;

create or replace function public.join_space(p_code text, p_password text)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user uuid := auth.uid();
  v_space public.spaces;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  perform public.current_profile();

  select * into v_space from public.spaces where space_code = upper(btrim(coalesce(p_code, '')));
  if not found then
    raise exception 'SPACE_NOT_FOUND';
  end if;
  if v_space.password_hash is null then
    raise exception 'JOIN_DISABLED';
  end if;
  if v_space.password_hash <> crypt(coalesce(p_password, ''), v_space.password_hash) then
    raise exception 'WRONG_PASSWORD';
  end if;

  insert into public.space_members (space_id, user_id, role)
  values (v_space.id, v_user, 'member')
  on conflict (space_id, user_id) do nothing;

  return v_space.id;
end;
$$;

create or replace function public.leave_space(p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_role text;
begin
  select role into v_role from public.space_members where space_id = p_space_id and user_id = v_user;
  if not found then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  if v_role = 'owner' then
    raise exception 'OWNER_CANNOT_LEAVE';
  end if;
  delete from public.space_members where space_id = p_space_id and user_id = v_user;
end;
$$;

create or replace function public.remove_space_member(p_space_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  if p_user_id = auth.uid() then
    raise exception 'OWNER_CANNOT_LEAVE';
  end if;
  delete from public.space_members where space_id = p_space_id and user_id = p_user_id;
end;
$$;

create or replace function public.delete_space(p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  delete from public.spaces where id = p_space_id;
end;
$$;

create or replace function public.create_box(p_space_id uuid, p_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := btrim(coalesce(p_name, ''));
  v_order integer;
  v_box_id uuid;
begin
  if not public.is_space_member(p_space_id) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'INVALID_BOX_NAME';
  end if;

  select coalesce(max(sort_order), -1) + 1 into v_order from public.boxes where space_id = p_space_id;

  insert into public.boxes (space_id, name, kind, sort_order)
  values (p_space_id, v_name, 'text', v_order)
  returning id into v_box_id;

  return v_box_id;
end;
$$;

create or replace function public.reorder_boxes(p_space_id uuid, p_box_ids uuid[])
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_space_member(p_space_id) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  update public.boxes b
  set sort_order = ordered.idx - 1
  from unnest(p_box_ids) with ordinality as ordered(box_id, idx)
  where b.id = ordered.box_id and b.space_id = p_space_id;
end;
$$;

create or replace function public.log_upgrade_intent(p_lever text, p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  insert into public.upgrade_intents (user_id, space_id, lever)
  values (v_user, p_space_id, p_lever);
end;
$$;

create or replace view public.space_summaries
with (security_invoker = true)
as
select
  s.id,
  s.name,
  s.space_code,
  s.owner_id,
  s.box_limit,
  s.quota_bytes,
  s.used_bytes,
  (s.password_hash is not null) as join_enabled,
  m.role,
  m.joined_at,
  (select count(*) from public.boxes b where b.space_id = s.id) as box_count,
  (select count(*) from public.space_members mm where mm.space_id = s.id) as member_count,
  s.created_at,
  s.updated_at
from public.spaces s
join public.space_members m on m.space_id = s.id and m.user_id = auth.uid();

create or replace view public.space_member_list
with (security_invoker = true)
as
select
  m.space_id,
  m.user_id,
  m.role,
  m.joined_at,
  p.display_name,
  p.email
from public.space_members m
join public.profiles p on p.id = m.user_id;

alter table public.plans enable row level security;
alter table public.profiles enable row level security;
alter table public.spaces enable row level security;
alter table public.space_members enable row level security;
alter table public.boxes enable row level security;
alter table public.upgrade_intents enable row level security;

drop policy if exists plans_read on public.plans;
create policy plans_read on public.plans
for select to authenticated using (true);

drop policy if exists profiles_read_self on public.profiles;
create policy profiles_read_self on public.profiles
for select to authenticated
using (id = auth.uid() or public.shares_space_with(id));

drop policy if exists spaces_read_member on public.spaces;
create policy spaces_read_member on public.spaces
for select to authenticated using (public.is_space_member(id));

drop policy if exists space_members_read on public.space_members;
create policy space_members_read on public.space_members
for select to authenticated using (public.is_space_member(space_id));

drop policy if exists boxes_read on public.boxes;
create policy boxes_read on public.boxes
for select to authenticated using (public.is_space_member(space_id));

drop policy if exists boxes_write on public.boxes;
create policy boxes_write on public.boxes
for update to authenticated
using (public.is_space_member(space_id))
with check (public.is_space_member(space_id));

drop policy if exists boxes_delete on public.boxes;
create policy boxes_delete on public.boxes
for delete to authenticated using (public.is_space_member(space_id));

drop policy if exists upgrade_intents_insert on public.upgrade_intents;
create policy upgrade_intents_insert on public.upgrade_intents
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists upgrade_intents_read on public.upgrade_intents;
create policy upgrade_intents_read on public.upgrade_intents
for select to authenticated using (user_id = auth.uid());

revoke all on public.plans from anon, authenticated;
revoke all on public.profiles from anon, authenticated;
revoke all on public.spaces from anon, authenticated;
revoke all on public.space_members from anon, authenticated;
revoke all on public.boxes from anon, authenticated;
revoke all on public.upgrade_intents from anon, authenticated;
revoke all on public.space_summaries from anon, authenticated;
revoke all on public.space_member_list from anon, authenticated;

grant usage on schema public to authenticated;
grant select on public.plans to authenticated;
grant select on public.profiles to authenticated;
grant select on public.spaces to authenticated;
grant select on public.space_members to authenticated;
grant select, update, delete on public.boxes to authenticated;
grant select, insert on public.upgrade_intents to authenticated;
grant select on public.space_summaries to authenticated;
grant select on public.space_member_list to authenticated;
grant usage, select on sequence public.upgrade_intents_id_seq to authenticated;

revoke all on function public.generate_space_code() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.boxes_before_write() from public, anon, authenticated;
revoke all on function public.boxes_sync_usage() from public, anon, authenticated;
revoke all on function public.enforce_box_limit() from public, anon, authenticated;
revoke all on function public.touch_updated_at() from public, anon, authenticated;

grant execute on function public.is_space_member(uuid) to authenticated;
grant execute on function public.is_space_owner(uuid) to authenticated;
grant execute on function public.shares_space_with(uuid) to authenticated;
grant execute on function public.current_profile() to authenticated;
grant execute on function public.create_space(text) to authenticated;
grant execute on function public.ensure_personal_space() to authenticated;
grant execute on function public.rename_space(uuid, text) to authenticated;
grant execute on function public.set_space_code(uuid, text) to authenticated;
grant execute on function public.set_space_password(uuid, text) to authenticated;
grant execute on function public.clear_space_password(uuid) to authenticated;
grant execute on function public.join_space(text, text) to authenticated;
grant execute on function public.leave_space(uuid) to authenticated;
grant execute on function public.remove_space_member(uuid, uuid) to authenticated;
grant execute on function public.delete_space(uuid) to authenticated;
grant execute on function public.create_box(uuid, text) to authenticated;
grant execute on function public.reorder_boxes(uuid, uuid[]) to authenticated;
grant execute on function public.log_upgrade_intent(text, uuid) to authenticated;

alter table public.boxes replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'boxes'
    ) then
      alter publication supabase_realtime add table public.boxes;
    end if;
  end if;
end
$$;

alter table public.spaces add column if not exists description text;

alter table public.boxes add column if not exists tags text[] not null default '{}';

create index if not exists boxes_tags_idx on public.boxes using gin (tags);

alter table public.plans add column if not exists member_limit integer;
alter table public.plans alter column member_limit drop not null;
alter table public.plans add column if not exists price_monthly_krw integer not null default 0;
alter table public.plans add column if not exists price_yearly_krw integer not null default 0;
alter table public.plans add column if not exists tag_limit integer not null default 5;

update public.plans set
  box_limit = 10, space_limit = 1, member_limit = null, tag_limit = 3,
  price_monthly_krw = 0, price_yearly_krw = 0
where code = 'free';

update public.plans set
  box_limit = 50, space_limit = 3, member_limit = null, tag_limit = 12,
  price_monthly_krw = 0, price_yearly_krw = 0
where code = 'pro';

update public.plans set
  box_limit = 100, space_limit = 10, member_limit = null, tag_limit = 30,
  price_monthly_krw = 0, price_yearly_krw = 0
where code = 'team';

update public.spaces s
set box_limit = p.box_limit + pr.extra_boxes,
    quota_bytes = p.quota_bytes,
    updated_at = now()
from public.profiles pr
join public.plans p on p.code = pr.plan
where s.owner_id = pr.id;

alter table public.space_members drop constraint if exists space_members_role_check;
alter table public.space_members add constraint space_members_role_check
  check (role in ('owner', 'admin', 'member'));

create table if not exists public.box_user_state (
  box_id uuid not null references public.boxes(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  is_favorite boolean not null default false,
  use_count integer not null default 0 check (use_count >= 0),
  last_used_at timestamptz,
  primary key (box_id, user_id)
);

create index if not exists box_user_state_recent_idx
  on public.box_user_state (user_id, last_used_at desc nulls last);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  event text not null check (event in (
    'signup', 'box_created', 'box_copied', 'box_inserted', 'search_used',
    'favorite_used', 'space_created', 'space_joined', 'upgrade_clicked',
    'upgrade_started', 'subscription_active', 'template_filled',
    'box_duplicated', 'context_saved', 'invite_created'
  )),
  props jsonb not null default '{}' check (pg_column_size(props) < 512),
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_event_idx
  on public.analytics_events (event, created_at desc);

create table if not exists public.subscriptions (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  plan text not null default 'free' references public.plans(code),
  status text not null default 'active'
    check (status in ('active', 'trialing', 'past_due', 'canceled', 'expired')),
  provider text,
  external_id text,
  trial_ends_at timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invitations (
  token text primary key,
  space_id uuid not null references public.spaces(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('admin', 'member')),
  expires_at timestamptz not null,
  max_uses integer not null default 20 check (max_uses > 0),
  uses integer not null default 0 check (uses >= 0),
  created_at timestamptz not null default now()
);

create index if not exists invitations_space_idx on public.invitations (space_id, created_at desc);

drop trigger if exists subscriptions_touch on public.subscriptions;
create trigger subscriptions_touch before update on public.subscriptions
for each row execute function public.touch_updated_at();

create or replace function public.sync_profile_plan()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_effective text;
begin
  if new.status in ('active', 'trialing') and (new.current_period_end is null or new.current_period_end > now()) then
    v_effective := new.plan;
  else
    v_effective := 'free';
  end if;

  update public.profiles
  set plan = v_effective,
      plan_expires_at = new.current_period_end,
      updated_at = now()
  where id = new.user_id;

  update public.spaces s
  set box_limit = p.box_limit + pr.extra_boxes,
      quota_bytes = p.quota_bytes,
      updated_at = now()
  from public.plans p, public.profiles pr
  where s.owner_id = new.user_id and p.code = v_effective and pr.id = new.user_id;

  return new;
end;
$$;

drop trigger if exists subscriptions_sync_plan on public.subscriptions;
create trigger subscriptions_sync_plan after insert or update on public.subscriptions
for each row execute function public.sync_profile_plan();

create or replace view public.box_list
with (security_invoker = true)
as
select
  b.id,
  b.space_id,
  b.name,
  b.kind,
  b.text_content,
  b.tags,
  b.byte_size,
  b.locked,
  b.sort_order,
  b.updated_at,
  b.updated_by,
  b.created_at,
  coalesce(u.is_favorite, false) as is_favorite,
  coalesce(u.use_count, 0) as use_count,
  u.last_used_at
from public.boxes b
left join public.box_user_state u on u.box_id = b.id and u.user_id = auth.uid();

create or replace function public.normalize_tags(p_tags text[], p_limit integer)
returns text[]
language plpgsql
immutable
as $$
declare
  v_tag text;
  v_clean text;
  v_out text[] := '{}';
begin
  if p_tags is null then
    return v_out;
  end if;
  foreach v_tag in array p_tags loop
    v_clean := btrim(regexp_replace(coalesce(v_tag, ''), '\s+', ' ', 'g'));
    if char_length(v_clean) between 1 and 16 and not (v_clean = any (v_out)) then
      v_out := array_append(v_out, v_clean);
    end if;
    if array_length(v_out, 1) >= p_limit then
      exit;
    end if;
  end loop;
  return v_out;
end;
$$;

create or replace function public.effective_plan(p_user_id uuid)
returns public.plans
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_code text;
  v_plan public.plans;
begin
  select plan into v_code from public.profiles where id = p_user_id;
  select * into v_plan from public.plans where code = coalesce(v_code, 'free');
  if not found then
    select * into v_plan from public.plans where code = 'free';
  end if;
  return v_plan;
end;
$$;

create or replace function public.current_subscription()
returns public.subscriptions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_row public.subscriptions;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  select * into v_row from public.subscriptions where user_id = v_user;
  if not found then
    insert into public.subscriptions (user_id) values (v_user)
    on conflict (user_id) do nothing;
    select * into v_row from public.subscriptions where user_id = v_user;
  end if;
  return v_row;
end;
$$;

create or replace function public.set_box_favorite(p_box_id uuid, p_favorite boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_space uuid;
begin
  select space_id into v_space from public.boxes where id = p_box_id;
  if v_space is null or not public.is_space_member(v_space) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  insert into public.box_user_state (box_id, user_id, is_favorite)
  values (p_box_id, v_user, coalesce(p_favorite, false))
  on conflict (box_id, user_id) do update set is_favorite = excluded.is_favorite;
end;
$$;

create or replace function public.touch_box(p_box_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_space uuid;
begin
  select space_id into v_space from public.boxes where id = p_box_id;
  if v_space is null or not public.is_space_member(v_space) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  insert into public.box_user_state (box_id, user_id, use_count, last_used_at)
  values (p_box_id, v_user, 1, now())
  on conflict (box_id, user_id) do update
    set use_count = public.box_user_state.use_count + 1,
        last_used_at = now();
end;
$$;

create or replace function public.set_box_tags(p_box_id uuid, p_tags text[])
returns text[]
language plpgsql
security definer
set search_path = public
as $$
declare
  v_space uuid;
  v_owner uuid;
  v_limit integer;
  v_clean text[];
begin
  select space_id into v_space from public.boxes where id = p_box_id;
  if v_space is null or not public.is_space_member(v_space) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  select owner_id into v_owner from public.spaces where id = v_space;
  select tag_limit into v_limit from public.effective_plan(v_owner);
  v_clean := public.normalize_tags(p_tags, coalesce(v_limit, 3));
  update public.boxes set tags = v_clean where id = p_box_id;
  return v_clean;
end;
$$;

create or replace function public.duplicate_box(p_box_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_src public.boxes;
  v_order integer;
  v_new uuid;
  v_name text;
begin
  select * into v_src from public.boxes where id = p_box_id;
  if not found or not public.is_space_member(v_src.space_id) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;

  v_name := left(v_src.name || ' 사본', 40);
  select coalesce(max(sort_order), -1) + 1 into v_order from public.boxes where space_id = v_src.space_id;

  insert into public.boxes (space_id, name, kind, text_content, tags, sort_order)
  values (v_src.space_id, v_name, v_src.kind, v_src.text_content, v_src.tags, v_order)
  returning id into v_new;

  return v_new;
end;
$$;

create or replace function public.log_event(p_event text, p_props jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_props jsonb;
begin
  if v_user is null then
    return;
  end if;
  select coalesce(jsonb_object_agg(item.key, item.value), '{}'::jsonb)
  into v_props
  from jsonb_each(coalesce(p_props, '{}'::jsonb)) item
  where item.key in ('surface', 'lever', 'plan', 'count', 'role', 'mode', 'reason')
    and (
      jsonb_typeof(item.value) in ('number', 'boolean')
      or (jsonb_typeof(item.value) = 'string' and char_length(item.value #>> '{}') <= 32)
    );
  insert into public.analytics_events (user_id, event, props)
  values (v_user, p_event, v_props);
exception
  when check_violation then
    return;
end;
$$;

create or replace function public.set_member_role(p_space_id uuid, p_user_id uuid, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_role text;
begin
  select role into v_actor_role from public.space_members
  where space_id = p_space_id and user_id = auth.uid();

  if v_actor_role is null or v_actor_role not in ('owner', 'admin') then
    raise exception 'NOT_SPACE_ADMIN';
  end if;
  if p_role not in ('admin', 'member') then
    raise exception 'INVALID_ROLE';
  end if;
  if p_user_id = auth.uid() then
    raise exception 'CANNOT_CHANGE_OWN_ROLE';
  end if;
  if exists (
    select 1 from public.space_members
    where space_id = p_space_id and user_id = p_user_id and role = 'owner'
  ) then
    raise exception 'CANNOT_CHANGE_OWNER_ROLE';
  end if;
  if v_actor_role = 'admin' and p_role = 'admin' then
    raise exception 'NOT_SPACE_OWNER';
  end if;

  update public.space_members set role = p_role
  where space_id = p_space_id and user_id = p_user_id;
end;
$$;

create or replace function public.create_invite(p_space_id uuid, p_role text, p_days integer)
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_actor_role text;
  v_token text;
  v_days integer := least(greatest(coalesce(p_days, 7), 1), 30);
  v_role text := coalesce(p_role, 'member');
  attempts integer := 0;
begin
  select role into v_actor_role from public.space_members
  where space_id = p_space_id and user_id = auth.uid();
  if v_actor_role is null or v_actor_role not in ('owner', 'admin') then
    raise exception 'NOT_SPACE_ADMIN';
  end if;
  if v_role not in ('admin', 'member') then
    raise exception 'INVALID_ROLE';
  end if;
  if v_role = 'admin' and v_actor_role <> 'owner' then
    raise exception 'NOT_SPACE_OWNER';
  end if;

  loop
    v_token := encode(gen_random_bytes(18), 'hex');
    exit when not exists (select 1 from public.invitations where token = v_token);
    attempts := attempts + 1;
    if attempts > 30 then
      raise exception 'INVITE_TOKEN_EXHAUSTED';
    end if;
  end loop;

  insert into public.invitations (token, space_id, created_by, role, expires_at)
  values (v_token, p_space_id, auth.uid(), v_role, now() + make_interval(days => v_days));

  return v_token;
end;
$$;

create or replace function public.peek_invite(p_token text)
returns table (space_name text, member_count bigint, expired boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inv public.invitations;
begin
  select * into v_inv from public.invitations where token = btrim(coalesce(p_token, ''));
  if not found then
    raise exception 'INVITE_NOT_FOUND';
  end if;
  return query
  select s.name,
         (select count(*) from public.space_members m where m.space_id = s.id),
         (v_inv.expires_at <= now() or v_inv.uses >= v_inv.max_uses)
  from public.spaces s
  where s.id = v_inv.space_id;
end;
$$;

create or replace function public.redeem_invite(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_inv public.invitations;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  perform public.current_profile();

  select * into v_inv from public.invitations where token = btrim(coalesce(p_token, '')) for update;
  if not found then
    raise exception 'INVITE_NOT_FOUND';
  end if;
  if v_inv.expires_at <= now() then
    raise exception 'INVITE_EXPIRED';
  end if;
  if v_inv.uses >= v_inv.max_uses then
    raise exception 'INVITE_EXHAUSTED';
  end if;

  if exists (select 1 from public.space_members where space_id = v_inv.space_id and user_id = v_user) then
    return v_inv.space_id;
  end if;

  insert into public.space_members (space_id, user_id, role)
  values (v_inv.space_id, v_user, v_inv.role)
  on conflict (space_id, user_id) do nothing;

  update public.invitations set uses = uses + 1 where token = v_inv.token;

  return v_inv.space_id;
end;
$$;

create or replace function public.revoke_invites(p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_role text;
begin
  select role into v_actor_role from public.space_members
  where space_id = p_space_id and user_id = auth.uid();
  if v_actor_role is null or v_actor_role not in ('owner', 'admin') then
    raise exception 'NOT_SPACE_ADMIN';
  end if;
  delete from public.invitations where space_id = p_space_id;
end;
$$;

alter table public.box_user_state enable row level security;
alter table public.analytics_events enable row level security;
alter table public.subscriptions enable row level security;
alter table public.invitations enable row level security;

drop policy if exists box_user_state_own on public.box_user_state;
create policy box_user_state_own on public.box_user_state
for select to authenticated using (user_id = auth.uid());

drop policy if exists analytics_read_own on public.analytics_events;
create policy analytics_read_own on public.analytics_events
for select to authenticated using (user_id = auth.uid());

drop policy if exists subscriptions_read_own on public.subscriptions;
create policy subscriptions_read_own on public.subscriptions
for select to authenticated using (user_id = auth.uid());

drop policy if exists invitations_read_admin on public.invitations;
create policy invitations_read_admin on public.invitations
for select to authenticated using (public.is_space_owner(space_id));

revoke all on public.box_user_state from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;
revoke all on public.subscriptions from anon, authenticated;
revoke all on public.invitations from anon, authenticated;
revoke all on public.box_list from anon, authenticated;

grant select on public.box_user_state to authenticated;
grant select on public.analytics_events to authenticated;
grant select on public.subscriptions to authenticated;
grant select on public.invitations to authenticated;
grant select on public.box_list to authenticated;

revoke all on function public.sync_profile_plan() from public, anon, authenticated;
revoke all on function public.normalize_tags(text[], integer) from public, anon, authenticated;
revoke all on function public.effective_plan(uuid) from public, anon, authenticated;
revoke all on function public.current_subscription() from public, anon, authenticated;
revoke all on function public.set_box_favorite(uuid, boolean) from public, anon, authenticated;
revoke all on function public.touch_box(uuid) from public, anon, authenticated;
revoke all on function public.set_box_tags(uuid, text[]) from public, anon, authenticated;
revoke all on function public.duplicate_box(uuid) from public, anon, authenticated;
revoke all on function public.log_event(text, jsonb) from public, anon, authenticated;
revoke all on function public.set_member_role(uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.create_invite(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.peek_invite(text) from public, anon, authenticated;
revoke all on function public.redeem_invite(text) from public, anon, authenticated;
revoke all on function public.revoke_invites(uuid) from public, anon, authenticated;

grant execute on function public.effective_plan(uuid) to authenticated;
grant execute on function public.current_subscription() to authenticated;
grant execute on function public.set_box_favorite(uuid, boolean) to authenticated;
grant execute on function public.touch_box(uuid) to authenticated;
grant execute on function public.set_box_tags(uuid, text[]) to authenticated;
grant execute on function public.duplicate_box(uuid) to authenticated;
grant execute on function public.log_event(text, jsonb) to authenticated;
grant execute on function public.set_member_role(uuid, uuid, text) to authenticated;
grant execute on function public.create_invite(uuid, text, integer) to authenticated;
grant execute on function public.peek_invite(text) to authenticated;
grant execute on function public.redeem_invite(text) to authenticated;
grant execute on function public.revoke_invites(uuid) to authenticated;

drop view if exists public.space_summaries;
create view public.space_summaries
with (security_invoker = true)
as
select
  s.id,
  s.name,
  s.space_code,
  s.owner_id,
  s.box_limit,
  s.quota_bytes,
  s.used_bytes,
  (s.password_hash is not null) as join_enabled,
  m.role,
  m.joined_at,
  (select count(*) from public.boxes b where b.space_id = s.id) as box_count,
  (select count(*) from public.space_members mm where mm.space_id = s.id) as member_count,
  s.created_at,
  s.updated_at,
  s.description
from public.spaces s
join public.space_members m on m.space_id = s.id and m.user_id = auth.uid();

revoke all on public.space_summaries from anon, authenticated;
grant select on public.space_summaries to authenticated;

create or replace function public.describe_space(p_space_id uuid, p_description text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_text text := nullif(btrim(coalesce(p_description, '')), '');
begin
  select role into v_role from public.space_members
  where space_id = p_space_id and user_id = auth.uid();
  if v_role is null or v_role not in ('owner', 'admin') then
    raise exception 'NOT_SPACE_ADMIN';
  end if;
  if v_text is not null and char_length(v_text) > 120 then
    raise exception 'INVALID_SPACE_DESCRIPTION';
  end if;
  update public.spaces set description = v_text, updated_at = now() where id = p_space_id;
end;
$$;

revoke all on function public.describe_space(uuid, text) from public, anon, authenticated;
grant execute on function public.describe_space(uuid, text) to authenticated;

insert into public.subscriptions (user_id)
select id from public.profiles
on conflict (user_id) do nothing;
