create extension if not exists pgcrypto with schema extensions;

create table if not exists public.plans (
  code text primary key check (code in ('free', 'pro', 'team')),
  label text not null,
  box_limit integer not null check (box_limit > 0),
  space_limit integer not null check (space_limit > 0),
  quota_bytes bigint not null check (quota_bytes > 0),
  file_max_bytes bigint not null check (file_max_bytes > 0),
  sort_order smallint not null
);

insert into public.plans (code, label, box_limit, space_limit, quota_bytes, file_max_bytes, sort_order)
values
  ('free', 'Free', 10, 1, 52428800, 15728640, 0),
  ('pro', 'Pro', 50, 3, 1073741824, 104857600, 1),
  ('team', 'Team', 100, 10, 5368709120, 104857600, 2)
on conflict (code) do update set
  label = excluded.label,
  box_limit = excluded.box_limit,
  space_limit = excluded.space_limit,
  quota_bytes = excluded.quota_bytes,
  file_max_bytes = excluded.file_max_bytes,
  sort_order = excluded.sort_order;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  plan text not null default 'free' references public.plans(code),
  plan_expires_at timestamptz,
  extra_spaces integer not null default 0 check (extra_spaces >= 0),
  extra_boxes integer not null default 0 check (extra_boxes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.spaces (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 40),
  space_code text not null unique check (space_code ~ '^[A-Z0-9][A-Z0-9-]{2,23}$'),
  password_hash text,
  owner_id uuid not null references public.profiles(id) on delete restrict,
  box_limit integer not null default 10 check (box_limit > 0),
  quota_bytes bigint not null default 52428800 check (quota_bytes > 0),
  used_bytes bigint not null default 0 check (used_bytes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.space_members (
  space_id uuid not null references public.spaces(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (space_id, user_id)
);

create index if not exists space_members_user_idx on public.space_members (user_id, joined_at);

create table if not exists public.boxes (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 40),
  kind text not null default 'text' check (kind in ('text', 'image', 'file')),
  text_content text,
  r2_key text,
  byte_size bigint not null default 0 check (byte_size >= 0),
  expires_at timestamptz,
  sort_order integer not null default 0,
  locked boolean not null default false,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint boxes_text_size check (text_content is null or octet_length(text_content) <= 10240),
  constraint boxes_kind_shape check (
    (kind = 'text' and r2_key is null and expires_at is null)
    or (kind in ('image', 'file') and text_content is null)
  )
);

create index if not exists boxes_space_order_idx on public.boxes (space_id, sort_order, created_at);

create table if not exists public.upgrade_intents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  space_id uuid references public.spaces(id) on delete set null,
  lever text not null check (lever in ('box_limit', 'space_quota', 'space_limit', 'file_upload')),
  created_at timestamptz not null default now()
);

create index if not exists upgrade_intents_user_idx on public.upgrade_intents (user_id, created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(coalesce(new.email, ''), '@', 1)
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email, display_name)
select
  u.id,
  u.email,
  coalesce(u.raw_user_meta_data ->> 'full_name', split_part(coalesce(u.email, ''), '@', 1))
from auth.users u
on conflict (id) do nothing;

create or replace function public.is_space_member(p_space_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.space_members m
    where m.space_id = p_space_id and m.user_id = auth.uid()
  );
$$;

create or replace function public.is_space_owner(p_space_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.space_members m
    where m.space_id = p_space_id and m.user_id = auth.uid() and m.role = 'owner'
  );
$$;

create or replace function public.shares_space_with(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.space_members mine
    join public.space_members theirs on theirs.space_id = mine.space_id
    where mine.user_id = auth.uid() and theirs.user_id = p_user_id
  );
$$;

create or replace function public.generate_space_code()
returns text
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  raw text;
  candidate text;
  attempts integer := 0;
begin
  loop
    raw := '';
    for i in 1..8 loop
      raw := raw || substr(alphabet, 1 + floor(random() * length(alphabet))::integer, 1);
    end loop;
    candidate := substr(raw, 1, 4) || '-' || substr(raw, 5, 4);
    exit when not exists (select 1 from public.spaces s where s.space_code = candidate);
    attempts := attempts + 1;
    if attempts > 50 then
      raise exception 'SPACE_CODE_EXHAUSTED';
    end if;
  end loop;
  return candidate;
end;
$$;

create or replace function public.boxes_before_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_space public.spaces;
  v_delta bigint;
begin
  if tg_op = 'UPDATE' then
    if old.locked and new.text_content is distinct from old.text_content then
      raise exception 'BOX_LOCKED';
    end if;
    new.space_id := old.space_id;
    new.kind := old.kind;
    new.locked := old.locked;
    new.created_at := old.created_at;
  end if;

  if new.kind = 'text' then
    new.r2_key := null;
    new.expires_at := null;
    new.byte_size := coalesce(octet_length(new.text_content), 0);
  end if;

  new.updated_at := now();
  new.updated_by := auth.uid();

  select * into v_space from public.spaces where id = new.space_id for update;
  if not found then
    raise exception 'SPACE_NOT_FOUND';
  end if;

  if tg_op = 'INSERT' then
    v_delta := new.byte_size;
  else
    v_delta := new.byte_size - old.byte_size;
  end if;

  if v_delta > 0 and v_space.used_bytes + v_delta > v_space.quota_bytes then
    raise exception 'SPACE_QUOTA_EXCEEDED';
  end if;

  return new;
end;
$$;

drop trigger if exists boxes_before_write on public.boxes;
create trigger boxes_before_write before insert or update on public.boxes
for each row execute function public.boxes_before_write();

create or replace function public.boxes_sync_usage()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.spaces
    set used_bytes = used_bytes + new.byte_size, updated_at = now()
    where id = new.space_id;
    return new;
  elsif tg_op = 'UPDATE' then
    if new.space_id = old.space_id then
      update public.spaces
      set used_bytes = greatest(0, used_bytes + (new.byte_size - old.byte_size)), updated_at = now()
      where id = new.space_id;
    else
      update public.spaces
      set used_bytes = greatest(0, used_bytes - old.byte_size), updated_at = now()
      where id = old.space_id;
      update public.spaces
      set used_bytes = used_bytes + new.byte_size, updated_at = now()
      where id = new.space_id;
    end if;
    return new;
  else
    update public.spaces
    set used_bytes = greatest(0, used_bytes - old.byte_size), updated_at = now()
    where id = old.space_id;
    return old;
  end if;
end;
$$;

drop trigger if exists boxes_sync_usage on public.boxes;
create trigger boxes_sync_usage after insert or update or delete on public.boxes
for each row execute function public.boxes_sync_usage();

create or replace function public.enforce_box_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer;
  v_count integer;
begin
  select box_limit into v_limit from public.spaces where id = new.space_id;
  select count(*) into v_count from public.boxes where space_id = new.space_id;
  if v_count >= v_limit then
    raise exception 'BOX_LIMIT_REACHED';
  end if;
  return new;
end;
$$;

drop trigger if exists boxes_enforce_limit on public.boxes;
create trigger boxes_enforce_limit before insert on public.boxes
for each row execute function public.enforce_box_limit();

create or replace function public.current_profile()
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_profile public.profiles;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  select * into v_profile from public.profiles where id = v_user;
  if not found then
    insert into public.profiles (id) values (v_user) returning * into v_profile;
  end if;
  return v_profile;
end;
$$;

create or replace function public.create_space(p_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_profile public.profiles;
  v_plan public.plans;
  v_owned integer;
  v_name text := btrim(coalesce(p_name, ''));
  v_space_id uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'INVALID_SPACE_NAME';
  end if;

  v_profile := public.current_profile();
  select * into v_plan from public.plans where code = v_profile.plan;
  select count(*) into v_owned from public.spaces where owner_id = v_user;

  if v_owned >= v_plan.space_limit + v_profile.extra_spaces then
    raise exception 'SPACE_LIMIT_REACHED';
  end if;

  insert into public.spaces (name, space_code, owner_id, box_limit, quota_bytes)
  values (
    v_name,
    public.generate_space_code(),
    v_user,
    v_plan.box_limit + v_profile.extra_boxes,
    v_plan.quota_bytes
  )
  returning id into v_space_id;

  insert into public.space_members (space_id, user_id, role)
  values (v_space_id, v_user, 'owner');

  return v_space_id;
end;
$$;

create or replace function public.ensure_personal_space()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_space_id uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  perform public.current_profile();

  select id into v_space_id from public.spaces where owner_id = v_user order by created_at limit 1;
  if v_space_id is not null then
    insert into public.space_members (space_id, user_id, role)
    values (v_space_id, v_user, 'owner')
    on conflict (space_id, user_id) do nothing;
    return v_space_id;
  end if;

  select space_id into v_space_id from public.space_members where user_id = v_user order by joined_at limit 1;
  if v_space_id is not null then
    return v_space_id;
  end if;

  return public.create_space('내 공간');
end;
$$;

create or replace function public.rename_space(p_space_id uuid, p_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := btrim(coalesce(p_name, ''));
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'INVALID_SPACE_NAME';
  end if;
  update public.spaces set name = v_name, updated_at = now() where id = p_space_id;
end;
$$;

create or replace function public.set_space_code(p_space_id uuid, p_code text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := upper(btrim(coalesce(p_code, '')));
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  if v_code !~ '^[A-Z0-9][A-Z0-9-]{3,23}$' then
    raise exception 'INVALID_SPACE_CODE';
  end if;
  if exists (select 1 from public.spaces where space_code = v_code and id <> p_space_id) then
    raise exception 'SPACE_CODE_TAKEN';
  end if;
  update public.spaces set space_code = v_code, updated_at = now() where id = p_space_id;
  return v_code;
end;
$$;

create or replace function public.set_space_password(p_space_id uuid, p_password text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  if char_length(coalesce(p_password, '')) < 6 then
    raise exception 'PASSWORD_TOO_SHORT';
  end if;
  update public.spaces
  set password_hash = crypt(p_password, gen_salt('bf', 10)), updated_at = now()
  where id = p_space_id;
end;
$$;

create or replace function public.clear_space_password(p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  update public.spaces set password_hash = null, updated_at = now() where id = p_space_id;
end;
$$;

create or replace function public.join_space(p_code text, p_password text)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user uuid := auth.uid();
  v_space public.spaces;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  perform public.current_profile();

  select * into v_space from public.spaces where space_code = upper(btrim(coalesce(p_code, '')));
  if not found then
    raise exception 'SPACE_NOT_FOUND';
  end if;
  if v_space.password_hash is null then
    raise exception 'JOIN_DISABLED';
  end if;
  if v_space.password_hash <> crypt(coalesce(p_password, ''), v_space.password_hash) then
    raise exception 'WRONG_PASSWORD';
  end if;

  insert into public.space_members (space_id, user_id, role)
  values (v_space.id, v_user, 'member')
  on conflict (space_id, user_id) do nothing;

  return v_space.id;
end;
$$;

create or replace function public.leave_space(p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_role text;
begin
  select role into v_role from public.space_members where space_id = p_space_id and user_id = v_user;
  if not found then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  if v_role = 'owner' then
    raise exception 'OWNER_CANNOT_LEAVE';
  end if;
  delete from public.space_members where space_id = p_space_id and user_id = v_user;
end;
$$;

create or replace function public.remove_space_member(p_space_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  if p_user_id = auth.uid() then
    raise exception 'OWNER_CANNOT_LEAVE';
  end if;
  delete from public.space_members where space_id = p_space_id and user_id = p_user_id;
end;
$$;

create or replace function public.delete_space(p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_space_owner(p_space_id) then
    raise exception 'NOT_SPACE_OWNER';
  end if;
  delete from public.spaces where id = p_space_id;
end;
$$;

create or replace function public.create_box(p_space_id uuid, p_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := btrim(coalesce(p_name, ''));
  v_order integer;
  v_box_id uuid;
begin
  if not public.is_space_member(p_space_id) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'INVALID_BOX_NAME';
  end if;

  select coalesce(max(sort_order), -1) + 1 into v_order from public.boxes where space_id = p_space_id;

  insert into public.boxes (space_id, name, kind, sort_order)
  values (p_space_id, v_name, 'text', v_order)
  returning id into v_box_id;

  return v_box_id;
end;
$$;

create or replace function public.reorder_boxes(p_space_id uuid, p_box_ids uuid[])
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_space_member(p_space_id) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  update public.boxes b
  set sort_order = ordered.idx - 1
  from unnest(p_box_ids) with ordinality as ordered(box_id, idx)
  where b.id = ordered.box_id and b.space_id = p_space_id;
end;
$$;

create or replace function public.log_upgrade_intent(p_lever text, p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  insert into public.upgrade_intents (user_id, space_id, lever)
  values (v_user, p_space_id, p_lever);
end;
$$;

create or replace view public.space_summaries
with (security_invoker = true)
as
select
  s.id,
  s.name,
  s.space_code,
  s.owner_id,
  s.box_limit,
  s.quota_bytes,
  s.used_bytes,
  (s.password_hash is not null) as join_enabled,
  m.role,
  m.joined_at,
  (select count(*) from public.boxes b where b.space_id = s.id) as box_count,
  (select count(*) from public.space_members mm where mm.space_id = s.id) as member_count,
  s.created_at,
  s.updated_at
from public.spaces s
join public.space_members m on m.space_id = s.id and m.user_id = auth.uid();

create or replace view public.space_member_list
with (security_invoker = true)
as
select
  m.space_id,
  m.user_id,
  m.role,
  m.joined_at,
  p.display_name,
  p.email
from public.space_members m
join public.profiles p on p.id = m.user_id;

alter table public.plans enable row level security;
alter table public.profiles enable row level security;
alter table public.spaces enable row level security;
alter table public.space_members enable row level security;
alter table public.boxes enable row level security;
alter table public.upgrade_intents enable row level security;

drop policy if exists plans_read on public.plans;
create policy plans_read on public.plans
for select to authenticated using (true);

drop policy if exists profiles_read_self on public.profiles;
create policy profiles_read_self on public.profiles
for select to authenticated
using (id = auth.uid() or public.shares_space_with(id));

drop policy if exists spaces_read_member on public.spaces;
create policy spaces_read_member on public.spaces
for select to authenticated using (public.is_space_member(id));

drop policy if exists space_members_read on public.space_members;
create policy space_members_read on public.space_members
for select to authenticated using (public.is_space_member(space_id));

drop policy if exists boxes_read on public.boxes;
create policy boxes_read on public.boxes
for select to authenticated using (public.is_space_member(space_id));

drop policy if exists boxes_write on public.boxes;
create policy boxes_write on public.boxes
for update to authenticated
using (public.is_space_member(space_id))
with check (public.is_space_member(space_id));

drop policy if exists boxes_delete on public.boxes;
create policy boxes_delete on public.boxes
for delete to authenticated using (public.is_space_member(space_id));

drop policy if exists upgrade_intents_insert on public.upgrade_intents;
create policy upgrade_intents_insert on public.upgrade_intents
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists upgrade_intents_read on public.upgrade_intents;
create policy upgrade_intents_read on public.upgrade_intents
for select to authenticated using (user_id = auth.uid());

revoke all on public.plans from anon, authenticated;
revoke all on public.profiles from anon, authenticated;
revoke all on public.spaces from anon, authenticated;
revoke all on public.space_members from anon, authenticated;
revoke all on public.boxes from anon, authenticated;
revoke all on public.upgrade_intents from anon, authenticated;
revoke all on public.space_summaries from anon, authenticated;
revoke all on public.space_member_list from anon, authenticated;

grant usage on schema public to authenticated;
grant select on public.plans to authenticated;
grant select on public.profiles to authenticated;
grant select on public.spaces to authenticated;
grant select on public.space_members to authenticated;
grant select, update, delete on public.boxes to authenticated;
grant select, insert on public.upgrade_intents to authenticated;
grant select on public.space_summaries to authenticated;
grant select on public.space_member_list to authenticated;
grant usage, select on sequence public.upgrade_intents_id_seq to authenticated;

revoke all on function public.generate_space_code() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.boxes_before_write() from public, anon, authenticated;
revoke all on function public.boxes_sync_usage() from public, anon, authenticated;
revoke all on function public.enforce_box_limit() from public, anon, authenticated;
revoke all on function public.touch_updated_at() from public, anon, authenticated;

grant execute on function public.is_space_member(uuid) to authenticated;
grant execute on function public.is_space_owner(uuid) to authenticated;
grant execute on function public.shares_space_with(uuid) to authenticated;
grant execute on function public.current_profile() to authenticated;
grant execute on function public.create_space(text) to authenticated;
grant execute on function public.ensure_personal_space() to authenticated;
grant execute on function public.rename_space(uuid, text) to authenticated;
grant execute on function public.set_space_code(uuid, text) to authenticated;
grant execute on function public.set_space_password(uuid, text) to authenticated;
grant execute on function public.clear_space_password(uuid) to authenticated;
grant execute on function public.join_space(text, text) to authenticated;
grant execute on function public.leave_space(uuid) to authenticated;
grant execute on function public.remove_space_member(uuid, uuid) to authenticated;
grant execute on function public.delete_space(uuid) to authenticated;
grant execute on function public.create_box(uuid, text) to authenticated;
grant execute on function public.reorder_boxes(uuid, uuid[]) to authenticated;
grant execute on function public.log_upgrade_intent(text, uuid) to authenticated;

alter table public.boxes replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'boxes'
    ) then
      alter publication supabase_realtime add table public.boxes;
    end if;
  end if;
end
$$;
