alter table public.spaces add column if not exists description text;

alter table public.boxes add column if not exists tags text[] not null default '{}';

create index if not exists boxes_tags_idx on public.boxes using gin (tags);

alter table public.plans add column if not exists member_limit integer not null default 3;
alter table public.plans add column if not exists price_monthly_krw integer not null default 0;
alter table public.plans add column if not exists price_yearly_krw integer not null default 0;
alter table public.plans add column if not exists tag_limit integer not null default 5;

update public.plans set
  box_limit = 10, space_limit = 1, member_limit = 3, tag_limit = 3,
  price_monthly_krw = 0, price_yearly_krw = 0
where code = 'free';

update public.plans set
  box_limit = 300, space_limit = 5, member_limit = 5, tag_limit = 12,
  price_monthly_krw = 4900, price_yearly_krw = 49000
where code = 'pro';

update public.plans set
  box_limit = 1000, space_limit = 20, member_limit = 200, tag_limit = 30,
  price_monthly_krw = 12900, price_yearly_krw = 129000
where code = 'team';

alter table public.space_members drop constraint if exists space_members_role_check;
alter table public.space_members add constraint space_members_role_check
  check (role in ('owner', 'admin', 'member'));

create table if not exists public.box_user_state (
  box_id uuid not null references public.boxes(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  is_favorite boolean not null default false,
  use_count integer not null default 0 check (use_count >= 0),
  last_used_at timestamptz,
  primary key (box_id, user_id)
);

create index if not exists box_user_state_recent_idx
  on public.box_user_state (user_id, last_used_at desc nulls last);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  event text not null check (event in (
    'signup', 'box_created', 'box_copied', 'box_inserted', 'search_used',
    'favorite_used', 'space_created', 'space_joined', 'upgrade_clicked',
    'upgrade_started', 'subscription_active', 'template_filled',
    'box_duplicated', 'context_saved', 'invite_created'
  )),
  props jsonb not null default '{}' check (pg_column_size(props) < 512),
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_event_idx
  on public.analytics_events (event, created_at desc);

create table if not exists public.subscriptions (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  plan text not null default 'free' references public.plans(code),
  status text not null default 'active'
    check (status in ('active', 'trialing', 'past_due', 'canceled', 'expired')),
  provider text,
  external_id text,
  trial_ends_at timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invitations (
  token text primary key,
  space_id uuid not null references public.spaces(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('admin', 'member')),
  expires_at timestamptz not null,
  max_uses integer not null default 20 check (max_uses > 0),
  uses integer not null default 0 check (uses >= 0),
  created_at timestamptz not null default now()
);

create index if not exists invitations_space_idx on public.invitations (space_id, created_at desc);

drop trigger if exists subscriptions_touch on public.subscriptions;
create trigger subscriptions_touch before update on public.subscriptions
for each row execute function public.touch_updated_at();

create or replace function public.sync_profile_plan()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_effective text;
begin
  if new.status in ('active', 'trialing') and (new.current_period_end is null or new.current_period_end > now()) then
    v_effective := new.plan;
  else
    v_effective := 'free';
  end if;

  update public.profiles
  set plan = v_effective,
      plan_expires_at = new.current_period_end,
      updated_at = now()
  where id = new.user_id;

  update public.spaces s
  set box_limit = p.box_limit + pr.extra_boxes,
      quota_bytes = p.quota_bytes,
      updated_at = now()
  from public.plans p, public.profiles pr
  where s.owner_id = new.user_id and p.code = v_effective and pr.id = new.user_id;

  return new;
end;
$$;

drop trigger if exists subscriptions_sync_plan on public.subscriptions;
create trigger subscriptions_sync_plan after insert or update on public.subscriptions
for each row execute function public.sync_profile_plan();

create or replace view public.box_list
with (security_invoker = true)
as
select
  b.id,
  b.space_id,
  b.name,
  b.kind,
  b.text_content,
  b.tags,
  b.byte_size,
  b.locked,
  b.sort_order,
  b.updated_at,
  b.updated_by,
  b.created_at,
  coalesce(u.is_favorite, false) as is_favorite,
  coalesce(u.use_count, 0) as use_count,
  u.last_used_at
from public.boxes b
left join public.box_user_state u on u.box_id = b.id and u.user_id = auth.uid();

create or replace function public.normalize_tags(p_tags text[], p_limit integer)
returns text[]
language plpgsql
immutable
as $$
declare
  v_tag text;
  v_clean text;
  v_out text[] := '{}';
begin
  if p_tags is null then
    return v_out;
  end if;
  foreach v_tag in array p_tags loop
    v_clean := btrim(regexp_replace(coalesce(v_tag, ''), '\s+', ' ', 'g'));
    if char_length(v_clean) between 1 and 16 and not (v_clean = any (v_out)) then
      v_out := array_append(v_out, v_clean);
    end if;
    if array_length(v_out, 1) >= p_limit then
      exit;
    end if;
  end loop;
  return v_out;
end;
$$;

create or replace function public.effective_plan(p_user_id uuid)
returns public.plans
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_code text;
  v_plan public.plans;
begin
  select plan into v_code from public.profiles where id = p_user_id;
  select * into v_plan from public.plans where code = coalesce(v_code, 'free');
  if not found then
    select * into v_plan from public.plans where code = 'free';
  end if;
  return v_plan;
end;
$$;

create or replace function public.current_subscription()
returns public.subscriptions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_row public.subscriptions;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  select * into v_row from public.subscriptions where user_id = v_user;
  if not found then
    insert into public.subscriptions (user_id) values (v_user)
    on conflict (user_id) do nothing;
    select * into v_row from public.subscriptions where user_id = v_user;
  end if;
  return v_row;
end;
$$;

create or replace function public.set_box_favorite(p_box_id uuid, p_favorite boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_space uuid;
begin
  select space_id into v_space from public.boxes where id = p_box_id;
  if v_space is null or not public.is_space_member(v_space) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  insert into public.box_user_state (box_id, user_id, is_favorite)
  values (p_box_id, v_user, coalesce(p_favorite, false))
  on conflict (box_id, user_id) do update set is_favorite = excluded.is_favorite;
end;
$$;

create or replace function public.touch_box(p_box_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_space uuid;
begin
  select space_id into v_space from public.boxes where id = p_box_id;
  if v_space is null or not public.is_space_member(v_space) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  insert into public.box_user_state (box_id, user_id, use_count, last_used_at)
  values (p_box_id, v_user, 1, now())
  on conflict (box_id, user_id) do update
    set use_count = public.box_user_state.use_count + 1,
        last_used_at = now();
end;
$$;

create or replace function public.set_box_tags(p_box_id uuid, p_tags text[])
returns text[]
language plpgsql
security definer
set search_path = public
as $$
declare
  v_space uuid;
  v_owner uuid;
  v_limit integer;
  v_clean text[];
begin
  select space_id into v_space from public.boxes where id = p_box_id;
  if v_space is null or not public.is_space_member(v_space) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;
  select owner_id into v_owner from public.spaces where id = v_space;
  select tag_limit into v_limit from public.effective_plan(v_owner);
  v_clean := public.normalize_tags(p_tags, coalesce(v_limit, 3));
  update public.boxes set tags = v_clean where id = p_box_id;
  return v_clean;
end;
$$;

create or replace function public.duplicate_box(p_box_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_src public.boxes;
  v_order integer;
  v_new uuid;
  v_name text;
begin
  select * into v_src from public.boxes where id = p_box_id;
  if not found or not public.is_space_member(v_src.space_id) then
    raise exception 'NOT_SPACE_MEMBER';
  end if;

  v_name := left(v_src.name || ' 사본', 40);
  select coalesce(max(sort_order), -1) + 1 into v_order from public.boxes where space_id = v_src.space_id;

  insert into public.boxes (space_id, name, kind, text_content, tags, sort_order)
  values (v_src.space_id, v_name, v_src.kind, v_src.text_content, v_src.tags, v_order)
  returning id into v_new;

  return v_new;
end;
$$;

create or replace function public.log_event(p_event text, p_props jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    return;
  end if;
  insert into public.analytics_events (user_id, event, props)
  values (v_user, p_event, coalesce(p_props, '{}'::jsonb));
exception
  when check_violation then
    return;
end;
$$;

create or replace function public.set_member_role(p_space_id uuid, p_user_id uuid, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_role text;
begin
  select role into v_actor_role from public.space_members
  where space_id = p_space_id and user_id = auth.uid();

  if v_actor_role is null or v_actor_role not in ('owner', 'admin') then
    raise exception 'NOT_SPACE_ADMIN';
  end if;
  if p_role not in ('admin', 'member') then
    raise exception 'INVALID_ROLE';
  end if;
  if p_user_id = auth.uid() then
    raise exception 'CANNOT_CHANGE_OWN_ROLE';
  end if;
  if exists (
    select 1 from public.space_members
    where space_id = p_space_id and user_id = p_user_id and role = 'owner'
  ) then
    raise exception 'CANNOT_CHANGE_OWNER_ROLE';
  end if;
  if v_actor_role = 'admin' and p_role = 'admin' then
    raise exception 'NOT_SPACE_OWNER';
  end if;

  update public.space_members set role = p_role
  where space_id = p_space_id and user_id = p_user_id;
end;
$$;

create or replace function public.create_invite(p_space_id uuid, p_role text, p_days integer)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  alphabet constant text := 'abcdefghijkmnpqrstuvwxyz23456789';
  v_actor_role text;
  v_token text;
  v_days integer := least(greatest(coalesce(p_days, 7), 1), 30);
  v_role text := coalesce(p_role, 'member');
  attempts integer := 0;
begin
  select role into v_actor_role from public.space_members
  where space_id = p_space_id and user_id = auth.uid();
  if v_actor_role is null or v_actor_role not in ('owner', 'admin') then
    raise exception 'NOT_SPACE_ADMIN';
  end if;
  if v_role not in ('admin', 'member') then
    raise exception 'INVALID_ROLE';
  end if;
  if v_role = 'admin' and v_actor_role <> 'owner' then
    raise exception 'NOT_SPACE_OWNER';
  end if;

  loop
    v_token := '';
    for i in 1..22 loop
      v_token := v_token || substr(alphabet, 1 + floor(random() * length(alphabet))::integer, 1);
    end loop;
    exit when not exists (select 1 from public.invitations where token = v_token);
    attempts := attempts + 1;
    if attempts > 30 then
      raise exception 'INVITE_TOKEN_EXHAUSTED';
    end if;
  end loop;

  insert into public.invitations (token, space_id, created_by, role, expires_at)
  values (v_token, p_space_id, auth.uid(), v_role, now() + make_interval(days => v_days));

  return v_token;
end;
$$;

create or replace function public.peek_invite(p_token text)
returns table (space_name text, member_count bigint, expired boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inv public.invitations;
begin
  select * into v_inv from public.invitations where token = btrim(coalesce(p_token, ''));
  if not found then
    raise exception 'INVITE_NOT_FOUND';
  end if;
  return query
  select s.name,
         (select count(*) from public.space_members m where m.space_id = s.id),
         (v_inv.expires_at <= now() or v_inv.uses >= v_inv.max_uses)
  from public.spaces s
  where s.id = v_inv.space_id;
end;
$$;

create or replace function public.redeem_invite(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_inv public.invitations;
  v_owner uuid;
  v_limit integer;
  v_members integer;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  perform public.current_profile();

  select * into v_inv from public.invitations where token = btrim(coalesce(p_token, '')) for update;
  if not found then
    raise exception 'INVITE_NOT_FOUND';
  end if;
  if v_inv.expires_at <= now() then
    raise exception 'INVITE_EXPIRED';
  end if;
  if v_inv.uses >= v_inv.max_uses then
    raise exception 'INVITE_EXHAUSTED';
  end if;

  if exists (select 1 from public.space_members where space_id = v_inv.space_id and user_id = v_user) then
    return v_inv.space_id;
  end if;

  select owner_id into v_owner from public.spaces where id = v_inv.space_id;
  select member_limit into v_limit from public.effective_plan(v_owner);
  select count(*) into v_members from public.space_members where space_id = v_inv.space_id;
  if v_members >= coalesce(v_limit, 3) then
    raise exception 'MEMBER_LIMIT_REACHED';
  end if;

  insert into public.space_members (space_id, user_id, role)
  values (v_inv.space_id, v_user, v_inv.role)
  on conflict (space_id, user_id) do nothing;

  update public.invitations set uses = uses + 1 where token = v_inv.token;

  return v_inv.space_id;
end;
$$;

create or replace function public.revoke_invites(p_space_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_role text;
begin
  select role into v_actor_role from public.space_members
  where space_id = p_space_id and user_id = auth.uid();
  if v_actor_role is null or v_actor_role not in ('owner', 'admin') then
    raise exception 'NOT_SPACE_ADMIN';
  end if;
  delete from public.invitations where space_id = p_space_id;
end;
$$;

alter table public.box_user_state enable row level security;
alter table public.analytics_events enable row level security;
alter table public.subscriptions enable row level security;
alter table public.invitations enable row level security;

drop policy if exists box_user_state_own on public.box_user_state;
create policy box_user_state_own on public.box_user_state
for select to authenticated using (user_id = auth.uid());

drop policy if exists analytics_read_own on public.analytics_events;
create policy analytics_read_own on public.analytics_events
for select to authenticated using (user_id = auth.uid());

drop policy if exists subscriptions_read_own on public.subscriptions;
create policy subscriptions_read_own on public.subscriptions
for select to authenticated using (user_id = auth.uid());

drop policy if exists invitations_read_admin on public.invitations;
create policy invitations_read_admin on public.invitations
for select to authenticated using (public.is_space_owner(space_id));

revoke all on public.box_user_state from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;
revoke all on public.subscriptions from anon, authenticated;
revoke all on public.invitations from anon, authenticated;
revoke all on public.box_list from anon, authenticated;

grant select on public.box_user_state to authenticated;
grant select on public.analytics_events to authenticated;
grant select on public.subscriptions to authenticated;
grant select on public.invitations to authenticated;
grant select on public.box_list to authenticated;

revoke all on function public.sync_profile_plan() from public, anon, authenticated;
revoke all on function public.normalize_tags(text[], integer) from public, anon, authenticated;

grant execute on function public.effective_plan(uuid) to authenticated;
grant execute on function public.current_subscription() to authenticated;
grant execute on function public.set_box_favorite(uuid, boolean) to authenticated;
grant execute on function public.touch_box(uuid) to authenticated;
grant execute on function public.set_box_tags(uuid, text[]) to authenticated;
grant execute on function public.duplicate_box(uuid) to authenticated;
grant execute on function public.log_event(text, jsonb) to authenticated;
grant execute on function public.set_member_role(uuid, uuid, text) to authenticated;
grant execute on function public.create_invite(uuid, text, integer) to authenticated;
grant execute on function public.peek_invite(text) to authenticated;
grant execute on function public.redeem_invite(text) to authenticated;
grant execute on function public.revoke_invites(uuid) to authenticated;

create or replace view public.space_summaries
with (security_invoker = true)
as
select
  s.id,
  s.name,
  s.description,
  s.space_code,
  s.owner_id,
  s.box_limit,
  s.quota_bytes,
  s.used_bytes,
  (s.password_hash is not null) as join_enabled,
  m.role,
  m.joined_at,
  (select count(*) from public.boxes b where b.space_id = s.id) as box_count,
  (select count(*) from public.space_members mm where mm.space_id = s.id) as member_count,
  s.created_at,
  s.updated_at
from public.spaces s
join public.space_members m on m.space_id = s.id and m.user_id = auth.uid();

revoke all on public.space_summaries from anon, authenticated;
grant select on public.space_summaries to authenticated;

create or replace function public.describe_space(p_space_id uuid, p_description text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_text text := nullif(btrim(coalesce(p_description, '')), '');
begin
  select role into v_role from public.space_members
  where space_id = p_space_id and user_id = auth.uid();
  if v_role is null or v_role not in ('owner', 'admin') then
    raise exception 'NOT_SPACE_ADMIN';
  end if;
  if v_text is not null and char_length(v_text) > 120 then
    raise exception 'INVALID_SPACE_DESCRIPTION';
  end if;
  update public.spaces set description = v_text, updated_at = now() where id = p_space_id;
end;
$$;

grant execute on function public.describe_space(uuid, text) to authenticated;

insert into public.subscriptions (user_id)
select id from public.profiles
on conflict (user_id) do nothing;
